from ..MultyType import LangType

__languages = {
    'ru': LangType.Language (

        #Bot Control
        p1='Добро пожаловать, {username}!',
        p2='Тут вы можете пройти какой-либо опрос, или же создать свой персональный опрос, а потом отправить его другим.',
        p3='Чтобы пройти опрос, перешлите пригласительное сообщение, которое вам прислали вместе с ссылкой на данный бот.',
        b1='Войти в аккаунт',#Deadp47
        b2='Получить такой же опрос',#Deadp47
        p4='Зарегистрируйтесь или войдите в аккаунт!',
        p5='Подтвердите ответ:',
        b3='Продолжить',
        b4='Редактировать ответ',
        p6='Отправьте новый ответ на вопрос выше в замен предыдущему:',
        p7='Поздравляю! Вы прошли данный опрос!\nЧтобы получить такой же опрос нажмите на кнопку ниже "Получить такой же опрос"',
        p8 = "Приветствую вас снова!\nВыберите, что вы хотите сделать в меню снизу, или пришлите сюда пригласительное сообщение к данному боту, если хотите пройти какой-либо опрос.\n\n*Мой опросы* - Данная кнопка, перешлет вас в меню с ващеми опросами.\n\n*Ответы* - Данная кнопка даст вам ответы каторые другие пользователи дали на все ващи опросы.\n\n*Помощь* - Данная кнопка перенаправит вас в меню с ответами на часто задаваемые вопросы и связью со службой поддержки.\n\n*⬅️* - Данная кнопка обозначает выход с аккаунта.",
        p9 = "Вы находитесь в меню, где есть ответы на некоторые вопросы и возможность написать нам в службу поддержки.\n\nВыберите действие:",
        p10 = 'Напишите нам на данный аккаунт [@AskerSupport](https://t.me/)\nМы можем не ответить сразу из-за большого количества запросов, поэтому оставьте свой отзыв или проблему, и мы ответим как можно быстрее!',
        p11 = "Идет обработка данных...",
        
        #E Derimo! findaca mia fost lene sa mut cu locul toate cuvintele shi am facut acest costili. Da shi asha pohui la aceia cit de curat e codul in acest project
        p11_a='Номер вопроса', 
        p11_b='Ключевое слово/фраза', 
        p11_c='Вопрос', 
        p11_d='Ответ',

        p12 = '[Вот ссылка на таблицу с ответами на ваши опросы.]({file_link})',
        p13 = 'Выберите действие:\n\n*Новый опрос* - Данная кнопка, создаст опрос по ващем настроекам.\n\n*⬅️* - Данная кнопка обозначает назат в преведущее меню\n\n*Осталные кнопки* - Данные кнопки, ваши опросы, на них написанно названия вашего опроса, которое вы ввьели при создание нового опроса. После нажатия на данные кнопки вы попадете в меню где можете редактировать полнастью выбранный опрос.\n\nВыберите действие или опрос:',
        p14 = "Нажмите на кнопку *Продолжить* если не хотите нечего изменять в ващех ответах, либо выберите номер вопроса на который хотите изменить ответ.",
        p15 = "Выберите действие:\n\n*Мой опросы* - Данная кнопка, перешлет вас в меню с ващеми опросами.\n\n*Ответы* - Данная кнопка даст вам ответы каторые другие пользователи дали на все ващи опросы.\n\n*Помощь* - Данная кнопка перенаправит вас в меню с ответами на часто задаваемые вопросы и связью со службой поддержки.\n\n*⬅️* - Данная кнопка обозначает выход с аккаунта.\n\nВыберите действие:",
        p16 = "Выберите действие:\n\n*Новый вопрос* - Данная кнопка, создает новый вопрос в данном опросе по ващем настроикам.\n\n*Изменить названия* - Данная кнопка, меняет названия данного опроса.\n\n*🚫Удалить опрос🚫* - Данная кнопка, удаляет данный опрос, все вопросы в нем и все пользовательские ответы на него.\n\n*⬅️* - Данная кнопка обозначает назат в преведущее меню\n\n*Осталные кнопки* - Данные кнопки, ваши вопросы в данном опросе, на них написанно текст вопроса. После нажатия на них, вы попадете в меню где можете редактировать полнастью выбранный вопрос.\n",
        p17 = "Выберите действие:\n\n*Редактировать текст* - Данная кнопка, позволяет вам изменить текст вопроса.\n\n*Редактировать формат ответов* - Данная кнопка, позволяет вам изменить тип ответа на вопрос.\n\n*Редактировать ответы* - Данная кнопка позваоляет редактировать ответы для вопросов, где вы выбрали тип ответов, кнопки.\n\n*Редактировать последовательность* - Данная кнопка, позволяет вам изменить очередь данного вопроса в опросе.\n\n*🚫Удалить вопрос🚫* - Данная кнопка, удалит данный вопрос из опроса и все пользователские ответы на него.\n\n*⬅️* - Данная кнопка обозначает назат в преведущее меню.\n",
        p18 = "Напишите ваш новый текст для вопроса:",
        p19= "*Вы уверены что хотите удалить данный опрос?*\nПри подтверждение данного действие удалитса все данные по поводу данного опроса и не будут подлежать возврату, подумайте хорошо!",
        p20 = "Выберите новый тип ответа на вопрос\n\n*Текст* - Данный тип означает что пользователи которые будут отвечать на данный вопрос будут отвечать в виде текстового сообщения.\n\n*Кнопки* - Данный тип означает что пользователи которые будут отвечать на данный вопрос будут отвечать ввиде нажатия кнопок с ответоми под самим вопросом.",
        p21 = "Вы изменили тип ответа на данный вопрос:\n*\"{ask}\"*\n\nТеперь тип ответа на вопроса будет в виде текста",
        p22 = "Напишите ваши варианты ответов, разделенные через данный знак хэштега, как в скобках (#), они будут отабражанны в виде кнопок под ващем вопросом:",
        p23 = 'Вы вышли из своего аккаунта!\n*Если вы потеряйте пороль к аккаунту - свежытесь с службой поддершке, либо из описанния к боту либо через кнопу в главном меню.*',
        p24 = "Вы изменили тип ответа на данный вопрос:\n*\"{ask}\"*\n\nТеперь тип ответа на вопроса будет в виде кнопок",
        p25 = "Вы успешно зарегистрировались!\n*Если вы потеряйте пороль к аккаунту - свежытесь с службой поддершке, либо из описанния к боту либо через кнопу в главном меню.*\n\nЧтобы узнать об каждой кнопки каторые вы ввидете внизу напишыте ```/start```",
        p26= "Вы изменили ответы на данный вопрос:\n*\"{ask[0][0]}\"*\n\nТеперь ответы будут такими:\n",
        p27= "Имя ващего аккаунта: {new_text}\nСоздайте пароль для вашего аккаунта:",
        p28= "Данное имя уже занято!\nВыберите, пожалуйста, другое:",
        p29= "Вы успешно заменили текст вопроса!\nТеперь он такой:\n*\"{message_text}\"*",
        p30= "Вы успешно удалили вопрос!\nВыберите действие:\n\n*Новый вопрос* - Данная кнопка, создает новый вопрос в данном опросе по ващем настроикам.\n\n*Изменить названия* - Данная кнопка, меняет названия данного опроса.\n\n*🚫Удалить опрос🚫* - Данная кнопка, удаляет данный опрос, все вопросы в нем и все пользовательские ответы на него.\n\n*⬅️* - Данная кнопка обозначает назат в преведущее меню\n\n*Осталные кнопки* - Данные кнопки, ваши вопросы в данном опросе, на них написанно текст вопроса. После нажатия на них, вы попадете в меню где можете редактировать полнастью выбранный вопрос.",
        p31="Вы вышли из меню регистрации!",
        p32="Напишите ваш вопрос:",
        p33="Чтобы создавать опросы и давать их другим, вы должны зарегистрировать аккаунт.\nВведите имя для вашего аккаунта:",
        p34="Вы создали вопрос:\n*\"{ask}\"*\n\nТип ответа на данный вопрос будет в виде текста",
        p35="Выберите действие:\n\n*Новый вопрос* - Данная кнопка, создает новый вопрос в данном опросе по ващем настроикам.\n\n*Изменить названия* - Данная кнопка, меняет названия данного опроса.\n\n*🚫Удалить опрос🚫* - Данная кнопка, удаляет данный опрос, все вопросы в нем и все пользовательские ответы на него.\n\n*⬅️* - Данная кнопка обозначает назат в преведущее меню\n\n*Осталные кнопки* - Данные кнопки, ваши вопросы в данном опросе, на них написанно текст вопроса. После нажатия на них, вы попадете в меню где можете редактировать полнастью выбранный вопрос.",
        p36="Выберите тип ответа на вопрос\n\n*Текст* - Данный тип означает что пользователи которые будут отвечать на данный вопрос будут отвечать в виде текстового сообщения.\n\n*Кнопки* - Данный тип означает что пользователи которые будут отвечать на данный вопрос будут отвечать ввиде нажатия кнопок с ответоми под самим вопросом.",
        p37="Напишите ваши варианты ответов, разделенные через данный знак в скобках (#), они будут отабражанны в виде кнопок под ващем вопросм:",
        p38="Вы вышли из меню входа в аккаунт!",
        p39="Вы создали вопрос:\n*\"{ask}\"*\n\nТип ответа на данный вопрос будет в виде кнопок",
        p40="Пароль к данному аккаунту {file.data[str(message.from_user.id)]['username']} неверен!\nПожалуйста, попробуйте снова:",
        p41="Ведите названия, по которым другие будут получать доступ к вашему опросу:",
        p42="Данное названия уже существует!\nПожалуйста, введите друго имя для вашего опроса:",
        p43="В название опроса нельзя использовать запятые (,) и косую черту (/).\nПожалуйста, введите друго имя для вашего опроса:",
        p44="Вы успешно создали новый опрос!\nВыберите действие:\n\n*Новый опрос* - Данная кнопка, создаст опрос по ващем настроекам.\n\n*⬅️* - Данная кнопка, вернет вас в преведущее меню.\n\n*Осталные кнопки* - Данные кнопки, ваши опросы, на них написанно названия вашего опроса, которое вы ввьели при создание нового опроса. После нажатия на данные кнопки вы попадете в меню где можете редактировать полнастью выбранный опрос.\n\nВыберите действие или опрос:",
        p45="Напишите новое название для этого опроса *\"{upath.data[str(message.from_user.id)].split('/')[2]}\"*:",
        p46='Пароль к данному аккаунту {file.data[str(message.from_user.id)]["username"]} неверен!\nПожалуйста, попробуйте снова:',
        p47="Вы успешно вошли в аккаунт!",
        p48="Вы успешно изменили названия опроса!\nВыберите действие:\n\n*Новый вопрос* - Данная кнопка, создает новый вопрос в данном опросе по ващем настроикам.\n\n*Изменить названия* - Данная кнопка, меняет названия данного опроса.\n\n*🚫Удалить опрос🚫* - Данная кнопка, удаляет данный опрос, все вопросы в нем и все пользовательские ответы на него.\n\n*⬅️* - Данная кнопка обозначает назат в преведущее меню\n\n*Осталные кнопки* - Данные кнопки, ваши вопросы в данном опросе, на них написанно текст вопроса. После нажатия на них, вы попадете в меню где можете редактировать полнастью выбранный вопрос.\n",
        p49="Имя аккаунта: {new_text}\nВведите пароль от аккаунта:", 
        p50="Вы успешно удалили опрос!\nВыберите действие:\n\n*Новый опрос* - Данная кнопка, создаст опрос по ващем настроекам.\n\n*⬅️* - Данная кнопка, вернет вас в преведущее меню.\n\n*Осталные кнопки* - Данные кнопки, ваши опросы, на них написанно названия вашего опроса, которое вы ввьели при создание нового опроса. После нажатия на данные кнопки вы попадете в меню где можете редактировать полнастью выбранный опрос.\n\nВыберите действие или опрос:",
        p51="Этого имени не существует!\nВведите, пожалуйста, существующее имя:",
        p52="Введите имя пользователя:",

        p53="Вы изменили ответы на данный вопрос:\n*\{ask}\*\n\nТеперь ответы будут такими:\n",

        #Action
        p54='Мой опросы',
        p55='Ответы',
        p56='Помощь',
        p57='⬅️',
        p58='Новый опрос',
        p59='Новый вопрос',
        p60='Изменить названия',
        p70='🚫Удалить опрос🚫',
        p71='Удалить',
        p72='Не удалять',
        p73='Редактировать текст',
        p74='Редактировать формат ответов',
        p75='Редактировать ответы',
        p76='Редактировать последовательность',
        p77='Связаться с службой поддержки',

      
        #Menu
        b6='Мой опросы',
        b7='Ответы',
        b8='Помощь',#Deadp47
        b9='Новый опрос',
        b10= 'Изменить названия',
        b11= '🚫Удалить опрос🚫',
        b12= 'Редактировать текст',
        b13= 'Редактировать формат ответов',
        b14= 'Редактировать ответы',
        b15= '🚫Удалить вопрос🚫',
        b16= 'Новый вопрос',
        b17= 'Связаться с службой поддержки',
        b18='Удалить',
        b19='Не удалять',
        b21='Текст',
        b22='Кнопки',
        b23 = 'Редактировать последовательность'
),
    'ro': LangType.Language(
        
        #BotControl
        p1='Bun venit, {username}!',
        p2='Aici puteți participa la orice sondaj sau creați propriul sondaj personal și apoi să-l trimiteți altora.',
        p3='Pentru a participa la sondaj, trimiteți mesajul de invitație primit împreună cu un link către acest bot.',
        b1='Conectare la cont',
        b2='Obțineți un sondaj similar',
        p4='Înregistrați-vă sau conectați-vă la contul dvs.!',
        p5='Confirmați răspunsul:',
        b3='Continuați',
        b4='Editați răspunsul',
        p6='Trimiteți un nou răspuns la întrebarea de mai sus pentru a-l înlocui pe cel anterior:',
        p7='Felicitări! Ați completat acest sondaj!\nPentru a obține un sondaj similar, apăsați pe butonul de mai jos "Obțineți un sondaj similar"',
        p8="Bine ai venit înapoi!\nAlegeți ce doriți să faceți în meniul de mai jos sau trimiteți aici un mesaj de invitație către acest bot, dacă doriți să participați la un sondaj.\n\n*Sondajele mele* - Acest buton vă va trimite în meniul cu sondajele dvs.\n\n*Răspunsuri* - Acest buton vă va oferi răspunsurile pe care alți utilizatori le-au dat la toate sondajele dvs.\n\n*Ajutor* - Acest buton vă va redirecționa către meniul cu răspunsuri la întrebările frecvente și legătura cu serviciul de asistență.\n\n*⬅️* - Acest buton reprezintă ieșirea din cont.",
        p9="Vă aflați în meniul unde găsiți răspunsuri la unele întrebări și aveți posibilitatea de a ne scrie pentru asistență.\n\nAlegeți o acțiune:",
        p10='Scrieți-ne pe acest cont [@AskerSupport](https://t.me/)\nEste posibil să nu vă răspundem imediat din cauza numărului mare de solicitări, așa că vă rugăm să lăsați feedback-ul sau problema și vom răspunde cât mai curând posibil!',
        p11="Se procesează datele...",
        
        p11_a='Numărul întrebării',
        p11_b='Cuvânt cheie/frază',
        p11_c='Întrebare',
        p11_d='Răspuns',
        
        p12='[Iată link-ul către tabelul cu răspunsurile la sondajele dvs.]({file_link})',
        p13='Alegeți o acțiune:\n\n*Sondaj nou* - Acest buton va crea un sondaj conform setărilor dvs.\n\n*⬅️* - Acest buton vă va duce înapoi la meniul anterior\n\n*Celelalte butoane* - Aceste butoane reprezintă sondajele dvs., iar titlul sondajului pe care l-ați introdus când ați creat sondajul. După ce apăsați pe aceste butoane, veți intra în meniul unde puteți edita complet sondajul selectat.\n\nAlegeți o acțiune sau un sondaj:',
        p14="Apăsați pe butonul *Continuați* dacă nu doriți să modificați nimic în răspunsurile dvs., sau alegeți numărul întrebării pe care doriți să o modificați.",
        p15="Alegeți o acțiune:\n\n*Sondajele mele* - Acest buton vă va trimite în meniul cu sondajele dvs.\n\n*Răspunsuri* - Acest buton vă va oferi răspunsurile pe care alți utilizatori le-au dat la toate sondajele dvs.\n\n*Ajutor* - Acest buton vă va redirecționa către meniul cu răspunsuri la întrebările frecvente și legătura cu serviciul de asistență.\n\n*⬅️* - Acest buton reprezintă ieșirea din cont.\n\nAlegeți o acțiune:",
        p16="Alegeți o acțiune:\n\n*Întrebare nouă* - Acest buton va crea o întrebare nouă în acest sondaj conform setărilor dvs.\n\n*Modificați titlul* - Acest buton vă permite să modificați titlul acestui sondaj.\n\n*🚫Ștergeți sondajul🚫* - Acest buton va șterge acest sondaj, toate întrebările din el și toate răspunsurile utilizatorilor.\n\n*⬅️* - Acest buton vă va duce înapoi la meniul anterior\n\n*Celelalte butoane* - Aceste butoane reprezintă întrebările dvs. în acest sondaj. După ce apăsați pe aceste butoane, veți intra în meniul unde puteți edita complet întrebarea selectată.",
        p17="Alegeți o acțiune:\n\n*Editați textul* - Acest buton vă permite să modificați textul întrebării.\n\n*Editați formatul răspunsurilor* - Acest buton vă permite să modificați tipul de răspuns la întrebare.\n\n*Editați răspunsurile* - Acest buton vă permite să editați răspunsurile pentru întrebările la care ați ales tipul de răspuns 'butoane'.\n\n*Editați secvența* - Acest buton vă permite să modificați ordinea acestei întrebări în sondaj.\n\n*🚫Ștergeți întrebarea🚫* - Acest buton va șterge această întrebare din sondaj și toate răspunsurile utilizatorilor.\n\n*⬅️* - Acest buton vă va duce înapoi la meniul anterior.",
        p18="Scrieți noul text pentru întrebare:",
        p19="*Sunteți sigur că doriți să ștergeți acest sondaj?*\nLa confirmare, această acțiune va șterge toate datele referitoare la acest sondaj și nu vor putea fi recuperate, gândiți-vă bine!",
        p20="Alegeți un nou tip de răspuns la întrebare\n\n*Text* - Acest tip înseamnă că utilizatorii care vor răspunde la această întrebare vor răspunde printr-un mesaj text.\n\n*Butoane* - Acest tip înseamnă că utilizatorii care vor răspunde la această întrebare vor răspunde apăsând butoane cu răspunsurile sub întrebare.",
        p21="Ați modificat tipul de răspuns pentru această întrebare:\n*\"{ask}\"*\n\nAcum, tipul de răspuns pentru întrebarea va fi text",
        p22="Scrieți variantele dvs. de răspuns, separate de semnul hashtag (#), acestea vor fi afișate sub întrebarea dvs. ca butoane:",
        p23='Ați ieșit din contul dvs.!\n*Dacă v-ați pierdut parola pentru cont - contactați serviciul de asistență, fie din descrierea botului, fie printr-un buton din meniul principal.*',
        p24="Ați modificat tipul de răspuns pentru această întrebare:\n*\"{ask}\"*\n\nAcum, tipul de răspuns pentru întrebarea va fi butoane",
        p25="V-ați înregistrat cu succes!\n*Dacă v-ați pierdut parola pentru cont - contactați serviciul de asistență, fie din descrierea botului, fie printr-un buton din meniul principal.*\n\nPentru a afla despre fiecare buton pe care îl vedeți mai jos, scrieți ```/start```",
        p26="Ați modificat răspunsurile pentru această întrebare:\n*\"{ask[0][0]}\"*\n\nAcum, răspunsurile vor fi următoarele:\n",
        p27="Numele contului dvs.: {new_text}\nCreați o parolă pentru contul dvs.:",
        p28="Acest nume este deja ocupat!\nAlegeți, vă rog, altul:",
        p29= "Ați înlocuit cu succes textul întrebării!\nAcum este astfel:\n*\"{message_text}\"*",
        p30= "Ați șters cu succes întrebarea!\nAlegeți acțiunea:\n\n*Întrebare nouă* - Această opțiune creează o întrebare nouă în această sondaj conform preferințelor tale.\n\n*Modifică titlul* - Această opțiune modifică titlul acestui sondaj.\n\n*🚫Șterge sondajul🚫* - Această opțiune șterge acest sondaj, toate întrebările din el și toate răspunsurile utilizatorilor.\n\n*⬅️* - Această opțiune reprezintă întoarcerea la meniul anterior.\n\n*Alte butoane* - Acestea sunt întrebările tale în acest sondaj, iar textul întrebării este afișat pe ele. După ce apeși pe ele, vei intra în meniul unde poți edita complet întrebarea selectată.",
        p31="Ai ieșit din meniul de înregistrare!",
        p32="Scrie-ți întrebarea:",
        p33="Pentru a crea sondaje și a le oferi altora, trebuie să îți creezi un cont. Introdu un nume pentru contul tău:",
        p34="Ai creat întrebarea:\n*\"{ask}\"*\n\nTipul de răspuns pentru această întrebare va fi sub formă de text",
        p35="Alegeți acțiunea:\n\n*Întrebare nouă* - Această opțiune creează o întrebare nouă în acest sondaj conform preferințelor tale.\n\n*Modifică titlul* - Această opțiune modifică titlul acestui sondaj.\n\n*🚫Șterge sondajul🚫* - Această opțiune șterge acest sondaj, toate întrebările din el și toate răspunsurile utilizatorilor.\n\n*⬅️* - Această opțiune reprezintă întoarcerea la meniul anterior.\n\n*Alte butoane* - Acestea sunt întrebările tale în acest sondaj, iar textul întrebării este afișat pe ele. După ce apeși pe ele, vei intra în meniul unde poți edita complet întrebarea selectată.",
        p36="Alegeți tipul de răspuns la întrebare\n\n*Text* - Acest tip indică faptul că utilizatorii care vor răspunde la această întrebare vor răspunde sub forma unui mesaj text.\n\n*Buton* - Acest tip indică faptul că utilizatorii care vor răspunde la această întrebare vor răspunde prin apăsarea butoanelor cu răspunsuri sub întrebare.",
        p37="Scrieți opțiunile dvs. de răspuns, separate prin acest semn în paranteze (#); ele vor fi afișate sub forma de butoane sub întrebarea dvs.:",
        p38="Ai ieșit din meniul de autentificare!",
        p39="Ai creat întrebarea:\n*\"{ask}\"*\n\nTipul de răspuns pentru această întrebare va fi sub formă de butoane",
        p40="Parola pentru acest cont {file.data[str(message.from_user.id)]['username']} este incorectă!\nTe rog să încerci din nou:",
        p41="Introduceți titlul după care alții pot accesa sondajul dvs.:",
        p42="Acest titlu există deja!\nTe rog să introduci un alt nume pentru sondajul tău:",
        p43="În titlul sondajului nu se pot folosi virgule (,) și linii oblice (/).\nTe rog să introduci alt nume pentru sondajul tău:",
        p44="Ai creat cu succes un sondaj nou!\nAlegeți acțiunea:\n\n*Un sondaj nou* - Această opțiune creează un sondaj conform preferințelor tale.\n\n*⬅️* - Această opțiune te întoarce la meniul anterior.\n\n*Alte butoane* - Acestea sunt sondajele tale, iar titlul sondajului pe care l-ai introdus când ai creat un nou sondaj este afișat pe ele. După ce apeși pe ele, vei intra în meniul unde poți edita complet sondajul selectat.\n\nAlegeți acțiunea sau sondajul:",
        p45="Scrieți un nou titlu pentru acest sondaj *\"{upath.data[str(message.from_user.id)].split('/')[2]}\"*:",
        p46='Parola pentru acest cont {file.data[str(message.from_user.id)]["username"]} este incorectă!\nTe rog să încerci din nou:',
        p47="Te-ai autentificat cu succes!",
        p48="Ai schimbat cu succes titlul sondajului!\nAlegeți acțiunea:\n\n*Un sondaj nou* - Această opțiune creează un sondaj conform preferințelor tale.\n\n*⬅️* - Această opțiune te întoarce la meniul anterior.\n\n*Alte butoane* - Acestea sunt sondajele tale, iar titlul sondajului pe care l-ai introdus când ai creat un nou sondaj este afișat pe ele. După ce apeși pe ele, vei intra în meniul unde poți edita complet sondajul selectat.\n",
        p49="Numele contului: {new_text}\nIntroduceți parola contului:",
        p50="Ai șters cu succes sondajul!\nAlegeți acțiunea:\n\n*Un sondaj nou* - Această opțiune creează un sondaj conform preferințelor tale.\n\n*⬅️* - Această opțiune te întoarce la meniul anterior.\n\n*Alte butoane* - Acestea sunt sondajele tale, iar titlul sondajului pe care l-ai introdus când ai creat un nou sondaj este afișat pe ele. După ce apeși pe ele, vei intra în meniul unde poți edita complet sondajul selectat.\n\nAlegeți acțiunea sau sondajul:",
        p51="Acest nume nu există!\nTe rog să introduci un nume existent:",
        p52="Introduceți numele utilizatorului:",
        p53="Ați modificat cu succes răspunsurile la această întrebare:\n*\{ask}\*\n\nAcum, răspunsurile vor fi următoarele:\n",

        #Action
        p54='Sondajele mele',
        p55='Răspunsuri',
        p56='Ajutor',
        p57='⬅️',
        p58='Sondaj nou',
        p59='Întrebare nouă',
        p60='Editare titluri',
        p70='🚫Șterge sondajul🚫',
        p71='Șterge',
        p72='Nu șterge',
        p73='Editează textul',
        p74='Editează formatul răspunsurilor',
        p75='Editează răspunsurile',
        p76='Editează secvența',
        p77='Contactează serviciul de asistență',


        # Meniu
        b6='Sondajele mele',
        b7='Răspunsuri',
        b8='Ajutor',
        b9='Sondaj nou',
        b10='Editare titluri',
        b11='🚫Șterge sondajul🚫',
        b12='Editează textul',
        b13='Editează formatul răspunsurilor',
        b14='Editează răspunsurile',
        b15='🚫Șterge întrebarea🚫',
        b16='Întrebare nouă',
        b17='Contactează serviciul de asistență',
        b18='Șterge',
        b19='Nu șterge',
        b21='Text',
        b22='Butoane',
        b23='Editează secvența'


    )
}

async def get_lang(lang: str='ru') -> LangType.Language:
    return __languages.get(lang)
